// <auto-generated />
using System;
using FlexiSpace.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlexiSpace.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712184658_verifyContract2")]
    partial class verifyContract2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Amentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.AvailabilitiesTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DaysOfWeek")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<long>("ShareSpaceDetailId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Specificdate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ShareSpaceDetailId");

                    b.ToTable("AvailabilitiesTimes");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.BussinessCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BussinessCategories");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Acreage")
                        .HasColumnType("numeric");

                    b.Property<string>("ContractSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("DurationUnit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LesseeCardAddress")
                        .HasColumnType("text");

                    b.Property<DateOnly>("LesseeCardIssuanceDate")
                        .HasColumnType("date");

                    b.Property<string>("LesseeId")
                        .HasColumnType("text");

                    b.Property<string>("LesseeName")
                        .HasColumnType("text");

                    b.Property<string>("LesseeNumberCard")
                        .HasColumnType("text");

                    b.Property<string>("LessorCardAddress")
                        .HasColumnType("text");

                    b.Property<DateOnly>("LessorCardIssuanceDate")
                        .HasColumnType("date");

                    b.Property<string>("LessorId")
                        .HasColumnType("text");

                    b.Property<string>("LessorName")
                        .HasColumnType("text");

                    b.Property<string>("LessorNumberCard")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("PrimaryBookingRequestId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("LesseeId");

                    b.HasIndex("LessorId");

                    b.HasIndex("PrimaryBookingRequestId");

                    b.HasIndex("SpaceId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.ContractVerification", b =>
                {
                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsLesseeAgreed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLessorAgreed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LesseeIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("LesseeSignatureData")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("LesseeSignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LessorIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("LessorSignatureData")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("LessorSignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.HasKey("ContractId");

                    b.ToTable("ContractVerifications");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Conversation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastMessage")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LesseeId")
                        .HasColumnType("text");

                    b.Property<string>("LessorId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LesseeId");

                    b.HasIndex("LessorId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Listing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AllowedEndTime")
                        .HasColumnType("date");

                    b.Property<DateOnly>("AllowedStartTime")
                        .HasColumnType("date");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatorId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ListingType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SpaceId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<string>("SenderId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.OperatingHour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time without time zone");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.ToTable("OperatingHours");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.PictureURL", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.Property<long?>("SpaceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserProfileId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("SpaceId");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("PictureURLs");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.PrimaryBookingRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("DurationUnit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpectedStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LesseeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LessorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal?>("OfferedPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<long?>("ReviewId1")
                        .HasColumnType("bigint");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LesseeId");

                    b.HasIndex("LessorId");

                    b.HasIndex("ListingId");

                    b.HasIndex("ReviewId1");

                    b.HasIndex("SpaceId");

                    b.ToTable("PrimaryBookingRequests");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingRequestId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewerId")
                        .HasColumnType("text");

                    b.Property<long>("SubBookingRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingRequestId")
                        .IsUnique();

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.ShareSpaceCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BussinessCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<long>("ShareSpaceDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BussinessCategoryId");

                    b.HasIndex("ShareSpaceDetailId");

                    b.ToTable("ShareSpaceCategory");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.ShareSpaceDetail", b =>
                {
                    b.Property<long>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsLegalCommitted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LegalCommittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaxSubRenter")
                        .HasColumnType("integer");

                    b.HasKey("ListingId");

                    b.ToTable("ShareSpaceDetails");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.SharedSpaceAmenities", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AmenityId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsIncluded")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("ShareSpaceDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AmenityId");

                    b.HasIndex("ShareSpaceDetailId");

                    b.ToTable("SharedSpaceAmenities");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Space", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<decimal>("Area")
                        .HasColumnType("numeric");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<string>("SpacePictures")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.SpaceAllowedCategory", b =>
                {
                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint");

                    b.Property<long>("BussinessCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("SpaceId", "BussinessCategoryId");

                    b.HasIndex("BussinessCategoryId");

                    b.ToTable("SpaceAllowedCategories");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<long?>("WalletId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.UserOTP", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpCode")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserOTPs");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("CitizenIDNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfIssue")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityCardNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PermanentResidence")
                        .HasColumnType("text");

                    b.Property<string>("SocialLink")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Wallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Amentity", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.Space", "Space")
                        .WithMany("Amenity")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Space");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.AvailabilitiesTime", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.ShareSpaceDetail", "ShareSpaceDetail")
                        .WithMany("AvailabilitiesTimes")
                        .HasForeignKey("ShareSpaceDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShareSpaceDetail");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Contract", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Contracts")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlexiSpace.Domain.Entities.User", "Lessee")
                        .WithMany()
                        .HasForeignKey("LesseeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlexiSpace.Domain.Entities.User", "Lessor")
                        .WithMany()
                        .HasForeignKey("LessorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlexiSpace.Domain.Entities.PrimaryBookingRequest", "PrimaryBookingRequest")
                        .WithMany("Contracts")
                        .HasForeignKey("PrimaryBookingRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlexiSpace.Domain.Entities.Space", "Space")
                        .WithMany("Contract")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Lessee");

                    b.Navigation("Lessor");

                    b.Navigation("PrimaryBookingRequest");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.ContractVerification", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.Contract", "Contract")
                        .WithOne("ContractVerification")
                        .HasForeignKey("FlexiSpace.Domain.Entities.ContractVerification", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.User", "Lessee")
                        .WithMany()
                        .HasForeignKey("LesseeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlexiSpace.Domain.Entities.User", "Lessor")
                        .WithMany()
                        .HasForeignKey("LessorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lessee");

                    b.Navigation("Lessor");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Listing", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.User", "Lessor")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlexiSpace.Domain.Entities.Space", "Space")
                        .WithMany("Listing")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lessor");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Message", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FlexiSpace.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.User", "User")
                        .WithMany("Notification")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.OperatingHour", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.Space", "Space")
                        .WithMany("OperatingHour")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Space");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.PictureURL", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.Listing", "Listing")
                        .WithMany("PictureURLs")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FlexiSpace.Domain.Entities.Space", "Space")
                        .WithMany("PictureURL")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FlexiSpace.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("Avatar")
                        .HasForeignKey("FlexiSpace.Domain.Entities.PictureURL", "UserProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Listing");

                    b.Navigation("Space");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.PrimaryBookingRequest", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.User", "Lessee")
                        .WithMany()
                        .HasForeignKey("LesseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlexiSpace.Domain.Entities.User", "Lessor")
                        .WithMany()
                        .HasForeignKey("LessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlexiSpace.Domain.Entities.Listing", "Listing")
                        .WithMany("PrimaryBookingRequests")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlexiSpace.Domain.Entities.Review", null)
                        .WithMany("PrimaryBookingRequest")
                        .HasForeignKey("ReviewId1");

                    b.HasOne("FlexiSpace.Domain.Entities.Space", "Space")
                        .WithMany("PrimaryBookingRequest")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lessee");

                    b.Navigation("Lessor");

                    b.Navigation("Listing");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Review", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.PrimaryBookingRequest", null)
                        .WithOne("Review")
                        .HasForeignKey("FlexiSpace.Domain.Entities.Review", "BookingRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlexiSpace.Domain.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlexiSpace.Domain.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Reviewer");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.ShareSpaceCategory", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.BussinessCategory", "BusinessCategory")
                        .WithMany()
                        .HasForeignKey("BussinessCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlexiSpace.Domain.Entities.ShareSpaceDetail", "ShareSpaceDetail")
                        .WithMany("ShareSpaceCategories")
                        .HasForeignKey("ShareSpaceDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessCategory");

                    b.Navigation("ShareSpaceDetail");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.ShareSpaceDetail", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.Listing", "Listing")
                        .WithOne("ShareSpaceDetail")
                        .HasForeignKey("FlexiSpace.Domain.Entities.ShareSpaceDetail", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.SharedSpaceAmenities", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.Amentity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlexiSpace.Domain.Entities.ShareSpaceDetail", "ShareSpaceDetail")
                        .WithMany("ShareSpaceAmenities")
                        .HasForeignKey("ShareSpaceDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("ShareSpaceDetail");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Space", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.SpaceAllowedCategory", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.BussinessCategory", "BussinessCategory")
                        .WithMany("SpaceAllowedCategories")
                        .HasForeignKey("BussinessCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlexiSpace.Domain.Entities.Space", "Space")
                        .WithMany("SpaceAllowedCategory")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BussinessCategory");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FlexiSpace.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.UserOTP", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.User", "User")
                        .WithMany("UserOTPs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("FlexiSpace.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("FlexiSpace.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.BussinessCategory", b =>
                {
                    b.Navigation("SpaceAllowedCategories");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Contract", b =>
                {
                    b.Navigation("ContractVerification");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Listing", b =>
                {
                    b.Navigation("PictureURLs");

                    b.Navigation("PrimaryBookingRequests");

                    b.Navigation("ShareSpaceDetail");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.PrimaryBookingRequest", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Review", b =>
                {
                    b.Navigation("PrimaryBookingRequest");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.ShareSpaceDetail", b =>
                {
                    b.Navigation("AvailabilitiesTimes");

                    b.Navigation("ShareSpaceAmenities");

                    b.Navigation("ShareSpaceCategories");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Space", b =>
                {
                    b.Navigation("Amenity");

                    b.Navigation("Contract");

                    b.Navigation("Listing");

                    b.Navigation("OperatingHour");

                    b.Navigation("PictureURL");

                    b.Navigation("PrimaryBookingRequest");

                    b.Navigation("SpaceAllowedCategory");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.User", b =>
                {
                    b.Navigation("Notification");

                    b.Navigation("Profile");

                    b.Navigation("UserOTPs");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("FlexiSpace.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
